package com.enclaveit.brea.entities;

// default package
// Generated Sep 9, 2015 1:45:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -4400102862593686789L;
    private Integer id;
    private String role;
    private String description;

    @JsonIgnore
    private Set<Users> userses = new HashSet<Users>(0);

    public Roles() {
    }

    public Roles(String role) {
        this.role = role;
    }

    public Roles(String role, String description, Set<Users> userses) {
        this.role = role;
        this.description = description;
        this.userses = userses;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

}