package com.enclaveit.brea.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;




// default package
// Generated Sep 9, 2015 1:45:50 PM by Hibernate Tools 3.4.0.CR1

/**
 * UsersInfo generated by hbm2java
 */
public class UsersInfo implements java.io.Serializable {

    /**
     *
     */
    private static final long serialVersionUID = -470537994415058598L;
    private int userId;
    @JsonIgnore
    private Users users;
    private String userFirstName;
    private String userLastName;
    private String userEmail;
    private String userPhone;
    private String userAddress;

    public UsersInfo() {
    }

    public UsersInfo(Users users) {
        this.users = users;
    }

    public UsersInfo(Users users, String userFirstName, String userLastName,
            String userEmail, String userPhone, String userAddress) {
        this.users = users;
        this.userFirstName = userFirstName;
        this.userLastName = userLastName;
        this.userEmail = userEmail;
        this.userPhone = userPhone;
        this.userAddress = userAddress;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getUserFirstName() {
        return this.userFirstName;
    }

    public void setUserFirstName(String userFirstName) {
        this.userFirstName = userFirstName;
    }

    public String getUserLastName() {
        return this.userLastName;
    }

    public void setUserLastName(String userLastName) {
        this.userLastName = userLastName;
    }

    public String getUserEmail() {
        return this.userEmail;
    }

    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }

    public String getUserPhone() {
        return this.userPhone;
    }

    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }

    public String getUserAddress() {
        return this.userAddress;
    }

    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

}
