package com.enclaveit.brea.entities;

// default package
// Generated Oct 8, 2015 3:33:46 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * VerificationToken generated by hbm2java
 */
public class VerificationToken implements java.io.Serializable {

    private int id;
    private Users users;
    private String token;
    private String username;
    private String tokenType;
    private Date expiresTime;

    public VerificationToken() {
    }

    public VerificationToken(Users users, String token, String username, String tokenType, Date expiresTime) {
        this.users = users;
        this.token = token;
        this.username = username;
        this.tokenType = tokenType;
        this.expiresTime = expiresTime;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getTokenType() {
        return this.tokenType;
    }

    public void setTokenType(String tokenType) {
        this.tokenType = tokenType;
    }

    public Date getExpiresTime() {
        return this.expiresTime;
    }

    public void setExpiresTime(Date expiresTime) {
        this.expiresTime = expiresTime;
    }

}
